name: Test build
on:
  pull_request:
    branches:
      - "main"

jobs:
  publish:
    name: Test build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      # Checkout Project
      - name: 📚 Checkout
        uses: actions/checkout@v2

      # Setup Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: docusaurus/package-lock.json

      # Build
      - name: 🔨 Build
        run: |
          bash ./scripts/build.sh
