name: Test build
on:
  pull_request:
    branches:
      - "main"

jobs:
  publish:
    name: Test build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      # Checkout Project
      - name: 📚 Checkout
        uses: actions/checkout@v2

      - name: Checkout Cloud Platform Source
        uses: actions/checkout@v3
        with:
          repository: hpcaitech/Cloud-Platform-Docs-Website
          token: ${{ secrets.CLOUD_PLATFORM_GITHUB_TOKEN }}
          path: Cloud-Platform-Docs-Website

      # Setup Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: Cloud-Platform-Docs-Website/cloud-platform-documentation/package-lock.json

      # Build
      - name: 🔨 Build
        run: |
          bash ./scripts/build.sh Cloud-Platform-Docs-Website
